### ISSUE TITLE
Tile Lighting pathes in random areas

### ISSUE THREAD

**Issue by luca-vm** [kaglet/cgv_project#19]
The lighting of the tiles is static in some places (If I move the maze grid the lighting pathces remain where they used to be)

**Comment by Shakeel-21** [comment]
yeah i dont think the light is originating from the tile as when it lights up the top of alex goes blue but the light should be coming from below

**Comment by mchlkavai** [comment]
The reason this happened was because of the distance and decay parameters of point lights. I've fixed this issue by resetting it all to 0.
